cms_shop/src/main/java/pl/riskyocelot/katrina/controller/NotebookEditorController.java
package pl.riskyocelot.katrina.controller;

import org.apache.log4j.Logger;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import pl.riskyocelot.katrina.model.GraphicsCard;
import pl.riskyocelot.katrina.model.Notebook;
import pl.riskyocelot.katrina.model.Processor;
import pl.riskyocelot.katrina.service.GraphicsCardService;
import pl.riskyocelot.katrina.service.NotebookService;
import pl.riskyocelot.katrina.service.ProcessorService;
import pl.riskyocelot.katrina.service.RamTypeService;

import java.util.List;

/**
 * Created by Sdfsgshg on 2016-02-06.
 */
@Controller
@RequestMapping("/edit")
public class NotebookEditorController {

    private static final Logger LOGGER = Logger.getLogger(NotebookEditorController.class);

    private final String INDEX = "edit/index";

    @Autowired
    private NotebookService notebookService;
    @Autowired
    private ProcessorService processorService;
    @Autowired
    private GraphicsCardService graphicsCardService;
    @Autowired
    private RamTypeService ramTypeService;

    @RequestMapping
    public String index()
    {
        return INDEX;
    }

    public void addNotebook()
    {
        Notebook notebook = new Notebook();

        notebookService.save(notebook);
    }

    public List<String> getProcessors() {
        LOGGER.info("Pobieranie nazw CPU");
        return processorService.getProcessorsName();
    }

    public List<String> getGraphicsCards() {
        LOGGER.info("Pobieranie nazw GPU");
        return graphicsCardService.getGraphicsCardsName();
    }

    public List<String> getRamTypes() {
        LOGGER.info("Pobieranie typow RAM");
        return ramTypeService.getRamTypes();
    }
}

cms_shop/src/main/webapp/edit/index.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
<f:view>
    <h:outputLabel value="Create new product"/>
</f:view>
<h:body>
    <h:selectOneMenu>
        <f:selectItems value="#{notebookEditorController.processors}"/>
    </h:selectOneMenu>
    <h:selectOneMenu>
        <f:selectItems value="#{notebookEditorController.graphicsCards}"/>
    </h:selectOneMenu>
    <p></p>
    <f:view>
        <h:outputLabel value="Nowy procesor"/>
        <h:form>
            <h:outputLabel value="Manufacturer"/>
            <h:inputText value="#{notebookBean.processor.manufacturer}"/>
            <h:outputLabel value="Series"/>
            <h:inputText value="#{notebookBean.processor.series}"/>
            <h:outputLabel value="Model"/>
            <h:inputText value="#{notebookBean.processor.model}"/>
            <h:outputLabel value="Clock speed down"/>
            <h:inputText value="#{notebookBean.processor.clockSpeedDown}"/>
            <h:outputLabel value="Clock speed up"/>
            <h:inputText value="#{notebookBean.processor.clockSpeedUp}"/>
            <h:outputLabel value="Cores"/>
            <h:inputText value="#{notebookBean.processor.cores}"/>
            <h:outputLabel value="Threads"/>
            <h:inputText value="#{notebookBean.processor.threads}"/>
            <h:outputLabel value="Cache L1"/>
            <h:inputText value="#{notebookBean.processor.cacheL1}"/>
            <h:outputLabel value="Cache L2"/>
            <h:inputText value="#{notebookBean.processor.cacheL2}"/>
            <h:outputLabel value="Cache L3"/>
            <h:inputText value="#{notebookBean.processor.cacheL3}"/>
            <h:outputLabel value="Params"/>
            <h:inputText value="#{notebookBean.processor.params}"/>
            <h:commandButton id="submit_cpu" value="Submit" action="#{notebookBean.addProcessor}"/>
        </h:form>
        <p></p>
        <h:outputLabel value="Nowa karta graficzna"/>
        <h:form>
            <h:outputLabel value="Manufacturer"/>
            <h:inputText value="#{notebookBean.graphicsCard.manufacturer}"/>
            <h:outputLabel value="Series"/>
            <h:inputText value="#{notebookBean.graphicsCard.series}"/>
            <h:outputLabel value="Model"/>
            <h:inputText value="#{notebookBean.graphicsCard.model}"/>
            <h:outputLabel value="Vram type"/>
            <h:inputText value="#{notebookBean.graphicsCard.vramType}"/>
            <h:outputLabel value="Vram size"/>
            <h:inputText value="#{notebookBean.graphicsCard.vramSize}"/>
            <h:commandButton id="submit_gpu" value="Submit" action="#{notebookBean.addGraphicsCard}"/>
        </h:form>
    </f:view>
</h:body>
</html>